[package]
name = "pushkind-todo"
version = "0.1.0"
edition = "2024"
default-run = "pushkind-todo"

[features]
default = ["server"]
data = ["pushkind-common"]
server = [
    "data",
    "actix-files",
    "actix-identity",
    "actix-multipart",
    "actix-session",
    "actix-web",
    "config",
    "csv",
    "dotenvy",
    "env_logger",
    "pushkind-emailer",
    "pushkind-common/actix",
    "pushkind-common/db",
    "pushkind-common/zeromq",
    "serde_html_form",
]

[[bin]]
name = "pushkind-todo"
path = "src/main.rs"
required-features = ["server"]

[dependencies]
actix-files = { version = "0.6.10", optional = true }
actix-identity = { version = "0.9.0", optional = true }
actix-multipart = { version = "0.7.2", optional = true }
actix-session = { version = "0.11.0", features = [
    "cookie-session",
], optional = true }
actix-web = { version = "4.13.0", optional = true }
chrono = { version = "0.4.44", features = ["serde"] }
csv = { version = "1.4.0", optional = true }
diesel = { version = "2.3.7", features = [
    "sqlite",
    "r2d2",
    "chrono",
    "returning_clauses_for_sqlite_3_35",
] }
dotenvy = { version = "0.15.7", optional = true }
env_logger = { version = "0.11.10", optional = true }
lazy_static = "1.5.0"
log = "0.4.29"
serde = { version = "1.0.228", features = ["derive"] }
serde_html_form = { version = "0.4.0", optional = true }
serde_json = "1.0.147"
thiserror = "2.0.18"
pushkind-common = { git = "https://github.com/pushkindt/pushkind-common.git", branch = "main", default-features = false, optional = true }
validator = { version = "0.20.0", features = ["derive"] }
ammonia = "4.1.2"
config = { version = "0.15.19", default-features = false, features = [
    "yaml",
], optional = true }
pushkind-emailer = { git = "https://github.com/pushkindt/pushkind-emailer.git", version = "0.1.0", features = [
    "data",
], default-features = false, optional = true }
uuid = { version = "1.23.0", features = ["v4", "serde"] }

[dev-dependencies]
diesel_migrations = "2.3.1"
mockall = "0.14.0"
tempfile = "3.27.0"
