server:
  address: 127.0.0.1
  port: 80
app:
  domain: ""
  database_url: app.db
  zmq_emailer_pub: tcp://127.0.0.1:5557
  secret: env::APP_SECRET
  auth_service_url: ""
  crm_service_url: ""
  zmq_tasks_pub: tcp://127.0.0.1:5563
