domain: ""
address: 127.0.0.1
port: 80
database_url: app.db
zmq_emailer_pub: tcp://127.0.0.1:5557
templates_dir: templates/**/*
secret: env::APP_SECRET
auth_service_url: ""
crm_service_url: ""
zmq_task_events_pub: tcp://127.0.0.1:5563
