name: Deploy development

on:
  push:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features
      - uses: actions/upload-artifact@v4
        with:
          name: pushkind-todo
          path: ./target/release/pushkind-todo
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v4
        with:
          name: pushkind-todo
          path: ./target/release/
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.CICD_PRIVATE_KEY }}
          name: id_rsa # optional
          known_hosts: ${{ secrets.CICD_KNOWN_HOSTS }}
          if_key_exists: fail # replace / ignore / fail; optional (defaults to fail)
      - name: Deploy
        run: |
          ssh cicd@users.pushkind.com "supervisorctl stop auth"
          scp ./target/release/pushkind-todo cicd@users.pushkind.com:/var/www10/html/
          scp -r ./assets/ cicd@users.pushkind.com:/var/www10/html/
          scp -r ./templates/ cicd@users.pushkind.com:/var/www10/html/
          scp -r ./migrations/ cicd@users.pushkind.com:/var/www10/html/
          ssh cicd@users.pushkind.com "cd /var/www10/html/ && /home/cicd/.cargo/bin/diesel migration run"
          ssh cicd@users.pushkind.com "supervisorctl start auth"
